### ISSUE TITLE
Proposal: Add a Variable object instead of using strings as variable names

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#34]
The current situation with variables as strings, makes it easy to make errors that can't be checked correctly by the interpreter and/or editors automatic code checking.

The simplest possible version would be something like:

```python
class Variable:
    def __init__(self, initial_value):
        self._value = initial_value
    
    @property
    def value(self):
        return self._value
    
    @value.setter
    def value(self, val):
        self._value = val
```

In a project, a user would then be able to write stuff like:
```
model.stupid_counter = Variable(0)

def step(model):
  model.stupid_counter += 1

model.line_chart(model.stupid_counter)
```

Some basic type checking could be added, such that a variable can't change type later on.

**Comment by dybber** [comment]
As I see it, the reason why we can't use traditional Python variables, is that we can't refer to them when defining graphs, sliders and monitors. I can't recall other places where that's necessary, but maybe I'm forgetting something?

Perhaps we shouldn't solve the problem by making a complex interface to define variables, but change how we define the various graphs, sliders and monitors.

Option 1: Use getattr(), globals() etc. to introspect variables 
---------
With this solution variables that should be graphed are given to e.g. `line_chart` functions as strings, and the function then does introspection to find the variable and monitor its value over time

```python
charge_flow = 17

line_chart("charge_flow") # use introspection to monitor global variable "charge_flow"
```

```python
class Electron:
  def setup(self):
      self.charged = False

  def step(self):
      ...
      self.charged = True
      ...

# bar_chart uses introspection to determine that charged is a boolean variable
# and makes a bar chart of how many Electron agents are True/False in their charged value, and keeps it updated over time.
bar_chart("Electron.charged")
```

Option 2: Make users call reporting functions, that updates the graphs
------------
The alternative to introspection might be to let users call reporting functions on line e.g. graph objects, when values change.

```
graph0 = line_graph("Title")
graph0.addSeries("x")
charge_flow = 0

def step(self):
    charge_flow = some_new_value
    graph0.add("x", charge_flow)
```

For sliders, this will probably perhaps not work, as what we need is for the sliders to update the variables, not the other way around. This might indicate that we should try Option 1 first.

**Comment by dybber** [comment]
To test whether Option 1 is possible, I created a small library to try to edit global variables in the importing module. However, a library is not able to read or edit global variables from the module importing it. This suggests that if we go with Option 1, we shouldn't at the same time go for removing the model object as suggested in #78.

The experiment
-------------
With the library defined in `testlib.py`
```python
#testlib.py
def inc(variable):
    globals()[variable] += 1
```

Used in another file or interactive prompt:
```python
import testlib
charge_flow = 17
inc("charge_flow")
```

Gives the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dpr964/Development/educational/AgentsPy/examples/testlib.py", line 5, in inc
    globals()[variable] += 1
KeyError: 'charge_flow'
```

What to do instead
-------------------
To combine these thoughts with some of what I tried to do in #78, we could perhaps go for an interface similar to this:

```
from agents import *

model = Model()

def setup():
    model.size(40, 80)
    model.title("Electricity")
    model.charge_flow = 17
    model.line_graph("charge_flow")

def step():
    ...

run(model, setup, step)
```
